### ISSUE TITLE
awsconfig/aws.go

### ISSUE THREAD

**Issue by rumarlon** [dynajoe/temporal-terraform-demo#1]
Currently running with `docker-compose up`.

Started the worker without issues.

Trying to use `awsconfig/aws.go` next.

```
$ go run aws.go
go run: cannot run non-main package
```

Is there another method that should be used for calling `aws.go`?

Thanks!

**Comment by rumarlon** [comment]
^ tl;dr trying to add my aws creds to test out your example.

**Comment by rumarlon** [comment]
changed aws.go to :
```
...
	awsConfig, err := config.LoadDefaultConfig(context.Background(), config.WithSharedConfigProfile("myawsprofile"))
...
```
ran: `go install aws.go`

worker log:
```
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: **********, host id: **********
2022/03/04 01:25:06 ERROR Activity error. Namespace default TaskQueue temporal-terraform-demo WorkerID 1153@mycomputer.localdomain@ WorkflowID demo-network RunID eb*****-*****-*****-******-******** ActivityType CreateVPCActivity Attempt 3 Error terraform error:
exit status 1
```

**Comment by rumarlon** [comment]
created s3 and updated the `Bucket:` name in:

`create_network.go`
`destroy_network.go`

**Comment by dynajoe** [comment]
To kick off workflows you can use `tctl` CLI. 

https://docs.temporal.io/docs/tctl/how-to-install-tctl

The `aws.go` file is for configuring AWS profile/creds. The entrypoint for this example is the worker at `cmd/main.go`.

**Comment by dynajoe** [comment]
In this example the AWS creds for the bucket and creating the vpc are the same. In practice, these may be different.

**Comment by rumarlon** [comment]
great success.  unblocked. thank you!!! 

```
...
aws_vpc.vpc: Creation complete after 6s [id=vpc-*******]
...
aws_subnet.subnet["us-west-2a"]: Creation complete after 2s [id=subnet-*****]
```
I have been using the tctl cmd from your demo video. ;) I didn't catch the creds were grabbed during the up. I was trying install after the up. Also helps to setup the shell with creds before up. ha.

follow-up questions 
(1): where can find a workflow registry for other examples?
(2): how do I configure for other cloud providers?

Many thanks for your help!!!

**Comment by rumarlon** [comment]
[google-cloud-go](https://github.com/googleapis/google-cloud-go)  👀 

This is starting to make more sense now... 😄
